---
- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 7200
  loop:
    - libffi-dev
    - libssl-dev
    - libjpeg-dev
    - zlib1g-dev
    - autoconf
    - build-essential
    - libopenjp2-7
    - libtiff5
    - libturbojpeg
    - tzdata
    - ffmpeg
  environment:
    HTTP_PROXY: http://192.168.3.1:8889
    HTTPS_PROXY: http://192.168.3.1:8889

- name: Copy service file
  ansible.builtin.copy:
    src: files/home-assistant.service
    dest: /etc/systemd/system/home-assistant@homeassistant.service

- name: Add the user homeassistant
  ansible.builtin.user:
    name: homeassistant
    create_home: yes
    shell: /bin/bash

- name: Create project folder
  ansible.builtin.file:
    name: /srv/homeassistant
    state: directory
    owner: homeassistant
    group: homeassistant

- name: Create venv
  become: yes
  become_user: homeassistant
  ansible.builtin.shell: python3.9 -m venv .
  args:
    chdir: /srv/homeassistant
    creates: bin/

- name: Install homeassistant
  become: yes
  become_user: homeassistant
  ansible.builtin.pip:
    name: homeassistant
    virtualenv: /srv/homeassistant
  environment:
    HTTP_PROXY: http://192.168.3.1:8889
    HTTPS_PROXY: http://192.168.3.1:8889

- name: Start home-assistant service
  ansible.builtin.systemd:
    name: home-assistant@homeassistant
    state: started
    daemon_reload: yes
    enabled: yes
