---
- name: Add apt source list for cloudflare
  ansible.builtin.copy:
    src: files/cloudflare-main.list
    dest: /etc/apt/sources.list.d/cloudflare-main.list

- name: Add apt key of cloudflare
  ansible.builtin.apt_key:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    state: present

- name: Install cloudflared package
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - cloudflared

- name: Create cloudflared config folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/cloudflared
    - ~/.cloudflared

- name: Copy cloudflared configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - src: templates/cloudflared-config.yaml
      dest: /etc/cloudflared/config.yml
      mode: '0755'
    - src: templates/cloudflare-creds.json
      dest: ~/.cloudflared/{{ TUNNEL_ID }}.json
      mode: '0600'

- name: Install cloudflared service
  ansible.builtin.shell: cloudflared service install

- name: Start cloudflared
  ansible.builtin.systemd:
    name: cloudflared
    enabled: yes
    state: started
