---
- name: Upgrade apt packages
  apt:
    upgrade: full
    update_cache: yes

- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 7200
  loop:
    - gpg
    - vim
    - ca-certificates
    - openjdk-11-jdk
