---
- name: Install NFS
  hosts: nfs
  become: yes
  roles:
    - role: 'roles/nfs'

- name: Install home-assistant
  become: yes
  hosts: home-assistant
  roles:
    - role: 'roles/home-assistant'

- name: Install postgresql
  become: yes
  hosts: postgresql
  roles:
    - role: 'roles/postgresql'

- name: Install Jenkins
  become: yes
  hosts: jenkins
  roles:
    - role: 'roles/jenkins'
