---
- name: Install NFS
  hosts: nfs
  become: yes
  roles:
    - role: 'roles/nfs'

- name: Install home-assistant
  hosts: home-assistant
  roles:
    - role: 'roles/home-assistant'

- name: Install minio
  hosts: minio
  roles:
    - role: 'roles/minio'
