---
- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 7200
  loop:
    - curl
    - vim

- name: Download minio
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    checksum: sha1:c28c4f03a5bf89e0566741180d001378ff0716ba
    mode: '0755'

- name: Download service file of minio
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
    dest: /etc/systemd/system/minio.service
    checksum: sha1:528b37138cb08eb045f97b33536af88261ecda2b
    mode: '0644'

- name: Copy default minio config
  ansible.builtin.template:
    src: templates/minio.conf.j2
    dest: /etc/default/minio

- name: Create data folder
  ansible.builtin.file:
    name: /data
    state: directory

- name: Enable minio service
  ansible.builtin.systemd:
    name: minio
    state: started
    enabled: yes
    daemon_reload: yes
